# Generated by Django 3.1 on 2020-08-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='summary',
            field=models.TextField(default='its okay'),
        ),
    ]
